name: playwright api and ui tests
# Когда запускаем
on: 
  push:
    branches:
      - main
# ручной запуск 
  workflow_dispatch:

jobs:
  eoTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
      - name: Установка npm пакеты из package.json
        run: npm ci
      - name: Установка браузеров
        run: npx playwright install --with-deps
      - name: запуск тестов
        run: npm t
        #todo внести в package.json
      - name: Сгенерировать allure 3 отчет в один файл
        run: npx allure awesome ./allure-results --single-file
        continue-on-error: true
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        continue-on-error: true
        with:
          name: allure single file
          patch: |
            allure-report/index.html
            allure-results
            playwright-report
        

